### PR TITLE
try again with macbookpro smc code

### PR DESCRIPTION
**Pull request by ysoftman**
It doesn't work in macbookpro.
so it's need to try again with macbookpro smc codes.

reference: https://logi.wiki/index.php/SMC_Sensor_Codes

### CODE REVIEW

**Comment by hacker1024** [comment]
Thanks for the PR!
One issue this raises is that on a MBP, the core list provided with the `-c` argument will be offset by one, which isn't great.
This can be avoided by checking if using TC0C gives zero (no matter what cores are requested) and offsetting the core integer by one based on that. Do you think you could do that instead?

**Comment by ysoftman** [comment]
I added core offset condition, Could you check the code ?

---
I am using bpytop tool and found that coretemp with no options is used in bpytop code.
https://github.com/aristocratos/bpytop/blob/8ecb9d3f4d650fe7dd1735c7f30069f4a2aca5b9/bpytop.py#L2827

**Comment by ivd-git** [comment]
I can confirm that this works like a charm on a MacBook Pro (Mid 2015 version) running OSX Catalina (10.15.7).

**Comment by hosamaly** [comment]
I, too, can confirm that it works on MacBook Pro (2018) running macOS 10.15.7

**Comment by hacker1024** [comment]
Sorry for the delay - I'll take a closer look tomorrow.

**Comment by denningsrogue** [comment]
Any updates?

**Comment by daxmc99** [comment]
This commit is required to run on a Macbook Pro 2019 othwerise I get 
`The specified core (0) does not exist.` by default

**Comment by Gusymochis** [comment]
Tested the PR on Macbook Pro 2017 Running Big Sur (11.0.1) and it's working as expected. Without the PR I also get the `The specified core (0) does not exist.` error.

**Comment by hacker1024** [comment]
Sorry for the wait; I'll merge this soon.

**Comment by hacker1024** [comment]
Can someone confirm if using the `-c` option works on a MBP now? I don't think this fixes it yet, as the offset is only calculated when specific cores aren't given.

The core numbering should start at 1.

**Comment by hosamaly** [comment]
Works on my machine. :)
```sh
$ coretemp -c 1,2,3,4,5,6
67
70
67
68
66
67
$ coretemp -c 0
The specified core (0) does not exist.
```

**Pull request merged**
